# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mannykoum/star_tracker_simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mannykoum/star_tracker_simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mannykoum/star_tracker_simulator/CMakeFiles /home/mannykoum/star_tracker_simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mannykoum/star_tracker_simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named star_tracker_input

# Build rule for target.
star_tracker_input: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 star_tracker_input
.PHONY : star_tracker_input

# fast build rule for target.
star_tracker_input/fast:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/build
.PHONY : star_tracker_input/fast

Star.o: Star.cpp.o
.PHONY : Star.o

# target to build an object file
Star.cpp.o:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/Star.cpp.o
.PHONY : Star.cpp.o

Star.i: Star.cpp.i
.PHONY : Star.i

# target to preprocess a source file
Star.cpp.i:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/Star.cpp.i
.PHONY : Star.cpp.i

Star.s: Star.cpp.s
.PHONY : Star.s

# target to generate assembly for a file
Star.cpp.s:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/Star.cpp.s
.PHONY : Star.cpp.s

hip_parser.o: hip_parser.cpp.o
.PHONY : hip_parser.o

# target to build an object file
hip_parser.cpp.o:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/hip_parser.cpp.o
.PHONY : hip_parser.cpp.o

hip_parser.i: hip_parser.cpp.i
.PHONY : hip_parser.i

# target to preprocess a source file
hip_parser.cpp.i:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/hip_parser.cpp.i
.PHONY : hip_parser.cpp.i

hip_parser.s: hip_parser.cpp.s
.PHONY : hip_parser.s

# target to generate assembly for a file
hip_parser.cpp.s:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/hip_parser.cpp.s
.PHONY : hip_parser.cpp.s

star_tracker_input.o: star_tracker_input.cpp.o
.PHONY : star_tracker_input.o

# target to build an object file
star_tracker_input.cpp.o:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/star_tracker_input.cpp.o
.PHONY : star_tracker_input.cpp.o

star_tracker_input.i: star_tracker_input.cpp.i
.PHONY : star_tracker_input.i

# target to preprocess a source file
star_tracker_input.cpp.i:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/star_tracker_input.cpp.i
.PHONY : star_tracker_input.cpp.i

star_tracker_input.s: star_tracker_input.cpp.s
.PHONY : star_tracker_input.s

# target to generate assembly for a file
star_tracker_input.cpp.s:
	$(MAKE) -f CMakeFiles/star_tracker_input.dir/build.make CMakeFiles/star_tracker_input.dir/star_tracker_input.cpp.s
.PHONY : star_tracker_input.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... star_tracker_input"
	@echo "... Star.o"
	@echo "... Star.i"
	@echo "... Star.s"
	@echo "... hip_parser.o"
	@echo "... hip_parser.i"
	@echo "... hip_parser.s"
	@echo "... star_tracker_input.o"
	@echo "... star_tracker_input.i"
	@echo "... star_tracker_input.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

